name: react-native-android-build-apk
on:
  push:
    branches:
      - development
jobs:
  install-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install npm dependencies
        run: |
          npm install
  build-android:
    needs: install-and-test
    runs-on: ubuntu-latest
    steps: 
      - uses: actions/checkout@v3
      - name: Install npm dependencies
        run: |
          npm install
      - name: Build Android Debug
        run: |
          cd android && ./gradlew assembleDebug
      - name: Upload Artifact
        uses: actions/upload-artifact@v1
        with:
          name: app-debug.apk
          path: android/app/build/outputs/apk/debug/
  Deploy:
    needs: install-and-test
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install npm dependencies
      run: npm i
    - name: Build OTA update
      uses: mrikirill/RN-AppCenter-CodePush@v1.0.0
      env:
        APPCENTER_TOKEN: ${{ secrets.APPCENTER_ACCESS_TOKEN }}
        APP_IOS: ReactFirst
        OTA_CHANNEL_IOS: Staging
        APP_ANDROID: ReactFirst
        OTA_CHANNEL_ANDROID: Staging
